const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=readFileSync(require('node:path').join(__dirname,'../dist/book.js'),'utf8');
const ocean={running:false,setRunning(value){this.running=value}};
const context=vm.createContext({active:null,holdingHome:false,reduced:{matches:false},document:{hidden:false},ids:['hero','work'],current:0,ocean});
vm.runInContext(source.match(/function syncOcean\(\)\{[\s\S]*?\n  \}/)[0],context);
const sync=()=>vm.runInContext('syncOcean()',context);
sync();assert.equal(ocean.running,true);
context.active={};sync();assert.equal(ocean.running,false);
context.active=null;context.current=1;sync();assert.equal(ocean.running,false);
context.current=0;sync();assert.equal(ocean.running,true);
context.holdingHome=true;sync();assert.equal(ocean.running,false);
context.holdingHome=false;sync();assert.equal(ocean.running,true);
context.document.hidden=true;sync();assert.equal(ocean.running,false);
context.document.hidden=false;context.reduced.matches=true;sync();assert.equal(ocean.running,false);
console.log('PASS: water pauses during turns, a finger held on Home, hidden pages/documents and reduced motion');
